version: '3.8'

services:

  spring-boot-app:
    build: .
    ports: # TODO allocate a different port here , need to remember which is external
      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/videonotes
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: password


#volumes:
#  postgres_data: