version: '3.8'

services:

  postgres:
    image: pgvector/pgvector:pg18-trixie # postgres PLUS vector db :)
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: videonotes
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql

  spring-boot-app:
    build: .
    ports:
      - "8070:8080"
#    depends_on:
#      - postgres
    environment:
      MEDIA_INPUT: /media-input
      TRANSCRIPT_OUTPUT: /transcript-output
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - ./media-input:/media-input
      - ./transcript-output:/transcript-output

#volumes:
#  postgres_data: