spring:
  application:
    name: video-notes-to-wiki

com:
  chaostensor:
    whisperwrapper:
      media-base-path: ${MEDIA_INPUT:./media-input} # TODO use an env var with a fallback to the process working dir / media