spring:
  profiles:
    # NOTE: Security: Caution: For now hosting only as an internal docker service used by a separate app in the same docker env.
    # The app currently exposes the transcribe operation, though that does let you specify a known path.
    # so in theory there is some risk of extracting transcripts from videos on disk if this were opened up.
    # not an issue for now but we'll probably want to add some server to server auth solution when we push this into eks.
    active: internal-only
  application:
    name: whisper-wrapper
  datasource:
    # for this app we only need the non reactive for liquibase.
    url: ${SPRING_VECTOR_DB_POSTGRES_DATASOURCE_URL:jdbc:postgresql://localhost:5432/video_notes}
    username: ${SPRING_VECTOR_DB_POSTGRES_DATASOURCE_USERNAME:user}
    password: ${SPRING_VECTOR_DB_POSTGRES_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: ${SPRING_R2DBC_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/video_notes}
    username: ${SPRING_R2DBC_DATASOURCE_USERNAME:user}
    password: ${SPRING_R2DBC_DATASOURCE_PASSWORD:password}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:1GB}
      max-request-size: ${MAX_REQUEST_SIZE:1025MB}

app:
  media-input: ${MEDIA_INPUT:./media-input} # TODO use an env var with a fallback to the process working dir / media
  transcript-output: ${TRANSCRIPT_OUTPUT:./transcript-output} # TODO use an env var with a fallback to the process working dir / media
  video-output: ${VIDEO_OUTPUT:./video-output}